apiVersion: v1
kind: Secret
metadata:
    name: freenas-smb-creds
    namespace: democratic-csi
stringData:
    mount_flags: ENC[AES256_GCM,data:U8DpCzEQQ9/C1DVhC91aK5gFeYs/ZAz4YvRgeiM9wl/2J6TvXglaEswjpfOTV23PyfkmHnIXP6WQSg==,iv:RNfYrYE5gt3yfcMDvjVHHmjhkBGHqevx/JJRhYq2TB4=,tag:JsuSXDwMjsMwf46FP4qalA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUnprZ0tFYitiRGRTVjdy
            ZExuajNrOVk5Qi8rZ210Q0ZJa2w4VFQvUDM4ClFrTkg1WXZScmFFVmlzOXhMTHMx
            dU9wYkNSbFN5VkxNbUNmcnNKQ0dTR2sKLS0tIGQxV0FJZGRCOGZrRmlWODYwWXlu
            MDk4UzJzWHRvdCtOQTQzcGdtOVBKQmsKsZ1QuxlNUfqPC9WGGNfI3TR3wbe2O573
            jKcIvHEwoyPVGE0/5mHCp5VIbzftQdhehk43qBseWcEYjouS9JbhsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T07:18:45Z"
    mac: ENC[AES256_GCM,data:/ic+1CQo+YS02QMMtDtkpq5icDnyJ3XUFKBXTEgOWsLJcX/OZOZBxTgpi/fw3cd0PyXdtMDlHJVyNT7Tjtku4UvDhfkKGNdKlmCzary1gPx6Egpc3bhJ6+e3osSeU3PuCuwTWiIr8F9OtObOq/Krg6+i+0mZrsW6GXpzBwXf3DA=,iv:xEFMh+PyhxIlgZ3TUcEcJWRIKN9h4l7jMJzwLglpEqo=,tag:eyye7v/AZ5N1oZrHPGjbMg==,type:str]
    pgp:
        - created_at: "2026-02-21T07:18:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+I2VD/7UlnfS628I4fWti90PYi7A/JY69z4A6QfKUjOSA
            FkKj4AH6B/o020IK8o47I3t1Z+vwv8aUohH7RTmdV6WqCbAgh+kaFIev6hU69a8h
            U1G7i7RkOGiD80ABmVYufwyCP2w0D+wuXMNKXB7dot9sfuQNjKNoV/ztXTMF4Qoz
            56KPs/pymFgxtuCq14kgs6HJ/qBmWFeE4A85/4ax8Z5mxPdp55PNdHpaCV4K1eRE
            3SPPKNzBYXjfJ5dz028z5LWcHBmAH+bG/Ka3HZWRaRu1iP2ZKnRATLaYU7iYkAtw
            vq16fDR5MPElZBJjYyfuDBjMdxmHuxi6IrIKPh3ubWDwiQDHlMzDe181i7rfiUx5
            80ytNBHh3SAIYYKn7wPwZSqODyml6giINkpQGEqKDIqxzjqRFLwE1Y++vo5eWU5+
            5WFzaZNqWCD01xwdOUA5+G9lRfqHDVM7H3OX4YVvLDuye0RBEONY+vBbxAIZ3ob9
            qWBn7Z1I0VuEtvW9Gj36YemaMivHbuNM+qbHgoRh2rbvPoxpOnw2Y2Qc6t1mu5i5
            w81HgF+lkPyVqG2EZvKRwzrTsvFqYwSGMsawkPh53XZ13ApxY1OYZbb5q5P+qJg8
            YUrG3vcAjZOck/Gg2eJzPzJKAOtgj9B2ZPtkzdd3RwPusgzIBD3FscMJgnfKd6LS
            UQFNypP5D3zej+wfmOvUD4a4JiNgiMu4x0OWMQDe4U6NPVx7PnfgrIlQU+74KFNI
            e+47DkkFmVYXTSvCdKo+nEVgXK/lbHXbAw+oGh+uXgaJww==
            =KqBK
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
