# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea-actions
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: gitea
  releaseName: gitea
  chart:
    spec:
      chart: actions
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    enabled: true
    existingSecret: gitea-actions
    existingSecretKey: RUNNER_TOKEN
    giteaRootURL: http://gitea-gitea-http.gitea.svc.cluster.local:3000
    global:
      storageClass: freenas-api-iscsi-csi
