apiVersion: v1
kind: Secret
metadata:
    name: gitea-actions
    namespace: gitea
stringData:
    RUNNER_TOKEN: ENC[AES256_GCM,data:0aTJ+HwcW79x0G5a5R3muEwU8JRk5qPOzmAqI1Zq55pm7+CYETGG8Q==,iv:+rRbZMGDdgEfyBuINcU64tVFeo+Ra8pGS7DwCnYwXRA=,tag:Zxr95fuqRWUQzyF7qT5bGg==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcGZOTHgvQlVKT0dxbUl4
            c2kwcGtmbEFBbnRNYWNvaXpWcXBTa3VzMUVVCmc5b0hBQXFBK0k4UDVwWlhQQlVE
            dDVoK1k4VHVhZ1RkcllQdnBTRW1qeTAKLS0tIDcrME5qRmRmWll0WWVXMld4QnZv
            SWZzV2R1QnZLekVTUlZEYVZDdG9tVjQKwuSf63QwQxIi+9zANDzr2Ez7uwwqx+Fa
            5pBNIM+HNKtCx+upuITgvhx73WAHiuLOLp1AQYIzBQPngf6eui2bmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T04:54:04Z"
    mac: ENC[AES256_GCM,data:XEQPVj7qVmxrNqR8mQnFglMTGAHdreix/EJztv3UIIUgYYi+z/lFmFeNgmg6AvzZlbnkrhFA2JpQHCDdCmXDneeq1eV7SfHfSD4JVIgbydPouBdgbZfz3WrvjKvyDLRWP7WagXN3E8OUv1+RldpRPWO4Im+uqCOoBAz7ac6lqns=,iv:Y17vY1zHNrfivlG6X672d8V4OVcXY8msHHLzsL9251U=,tag:2vLMPGhzmIrD5mLGf2+viQ==,type:str]
    pgp:
        - created_at: "2025-11-24T04:54:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ/+OIU1ryR+9dwdhVwnBvV0mVUrGeBj9wR4Tu+sBkmVaONC
            RA747Bdab++oI3ZNOE1BrjRRqb1Rk2QRtmkvSxNjwAUX4RK/Ww9+fQNubj3vr177
            5i7mn20WlzoOHKqIbKwtAjm8CTSn1iDOLaVAezsMqN0KDa70gG1sAzixdvPD77gf
            SfO8zxQqowtASc0WQ1IUjqRBhrBhda4fjHPP7GVD7iDeayvl0xPT0MxigowARxOc
            M18JS9kPjDXzr4x9c2h/qnaLWLd4ND2Dd8iWgxefOOia/0wgZRp+aEX7sScGrBPV
            jZ8yAxcrUzpw/0sgdkSWZcGThKxw/P6zH4IDkXzQl+SFNPp/hZY6qKkNgNWXeHyV
            N8CPU3Q+YIYt5kX40huZi/XxQ3jv30x742pPP8t6p7a/wZmIcu2kr1eucyo3wfGd
            7AHmrwULMNCHpWmRWectnhFlR+RrzAw7S7mQrBWvlokzdnqb9wDp2kXkpe4W1r8r
            bQYUrN9axC9qLU0h/93Gk3Dl6JrC/wQ7orZN//oC9NFlRW6rHg3/+e4VQ9BT4ZsZ
            aF8Jc82uqln6D52dYQ4rKHhr7UObjWP3a95pm7fL4hHtQfJDDtVx/9sIJTEVKlkj
            avngV57T2Q29eE13r2CszlSJS0//hjDmYOxU06rQYRv0mpY3RdqHvVtHn84IvmnS
            XgEkQZwxU3buB7vAaqwaU+wHq05JeInxGcqgAjAm0v9VHRH1pY1h0O1yHIzdQMua
            0VHqUTzXGYfU2XKl8gvGIisKWjAVAzxS4AxwXPz5ZC1qyg0jU4r9P556yBu/944=
            =90uY
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
