apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
    namespace: gitea
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:pUxvOuFr8ejq0EVxKIxOBvmbFCpCA9Vxs0NQKTJRr9AT4e1sl7nB/w==,iv:U1UOLTR7tgsFFIe7ngpAHWlNKPHIhvidK2i7r+5wFZI=,tag:CXEtJPVrXyrmDnpkcZg29w==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:FTcV/cwwZFUYidVgceWMLuV8RhYns9KY/XzYrxFs9i+WYzCFQu8TzH1Vfo7E+OJ4UaIrQimux1QReqej0i5wPHhE81KPgOvKpajlQyeEd3CwIZPFujKMUKTiX/3A,iv:WO4zC16/CYEDssUsICdUKddTj4i61EBN8id+aRDGiIs=,tag:1tLnwga2Lk37j5DSpoqAew==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QmEvaVVTQ3pwOE9OTEFC
            Q2RCSDhzOTZlYmFQemg2ZitjS0JPby9jMWdFCkpyWHgyV2l0OXVMeHdXS3BzMGp5
            eHh6MkpmdzFHc1h2NGpHQnA0NHAvSGMKLS0tIE9Zci9lWUlscVZ3RXBTT1d1SFU3
            ZzVjckU1bVNrMjJHZ09UdFkydzZxeDQKc1/y2hRAyzPrWXENEiGN32frHuay7mHc
            jnkKQS2wcvJlUUwaSityCMHbRwC0quxvzUNOhYOM7KuR2X4UAaq+1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T22:51:31Z"
    mac: ENC[AES256_GCM,data:j0Slgcndm9k9gu4Pf8x+JQK/K4Acmo87cnXJ6VC9PKJ9PqgdlMRjMs4bgITJe8iIQOEYPbUJzuULKKvoWrs16vGm3emrsf4pgyqXG01DMxCW7dlx7WDhMkzg34CSVmf/x+anv/WWn7LFDbLPTrxK9QSvJnGdvDyqP8nWFpKeJXo=,iv:R/Su2x9YvqMc5bTJPwwdsqkZjaq28BXJ5jHB2HAJ2L8=,tag:wMCGUdS/HITV90kkaBvO+w==,type:str]
    pgp:
        - created_at: "2025-11-27T22:51:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//df3oqAeOnyyHGQmA4115IypCvHaxiK/a31Eai13S8fDv
            vtV28bfffAN/QrPWQF+3sJWJM+pUsuffJ2Fsh8nwsprdancdeuFGQMS9Vto0wHgk
            TijKY5n9s47dQ3v0dg8ri8wFmdzN+sB/laaCJIpjFv/4FPa0HhzTeBTD30fORM7X
            0ijlF2wXt7o1gkKhMKdg30jC912uKooONc/hc9po1jHZ9kkAh5ENY4PUQsjIplG5
            L4lPshuG3uiW/AoU6aydE1s//8szoDjWuhTmrzrzjp8Lqk3w5jd4m7TXRIlDJTV4
            r++zcAbP3nG8hNJ+HvFPr9DTgVMvwzZ16hVSGGzitBvyUILxdcUyhuQAlxEE3xZ4
            OVM09TEC2UQKOIS/yrSY9uXrV2BVZyz0Gy4HXtvNl9GgOBra3mxbPEFicPZVqihO
            JekZwsyfksuQ+sFCNRXmM1iKhez/a+GDLoTq8dJrUEayRPbU5+43DctNY+G+gJqW
            0u8zLz/JEaSfL68jgevL590JBkaO8A2dkqzT0StZLYaSY1x9UfRnGaGv4pe92lD6
            EdSVYgTdZm463Aed/zvHNzSoQ27XTYFCScHjuRP89Hz10xaSXxsOgULl8pwS0ZYp
            cw/aWXBgHH4iPDu6x3V+LtJiT3IjLIHTFOZDHDZZ5nvIEJLYLD6i09v7v7H5AtTS
            XgEOH1rVV6K/MfWhA2kBoyMlmTF6VPhuGZ9O9GW6fYtD17bhdUrU81VvuSwl05jh
            FZkRCqvZj3ECldR6opmpA6mOk2hNqv90IA6jUWM90c5lLwANMFnwb1darseqv6Q=
            =y6S+
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
