apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: immich-pg-local-backup-base
  namespace: immich
spec:
  cluster:
    name: immich-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
