apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.k8s.yaml
  - deployment.k8s.yaml
  - svc.k8s.yaml
configMapGenerator:
  - name: blocky-config
    namespace: blocky
    files:
      - config.yaml
