apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/instance: blocky
spec:
  type: LoadBalancer
  loadBalancerIP: "${SVC_DNS_ADDR}"
  selector:
    app.kubernetes.io/name: blocky
    app.kubernetes.io/instance: blocky
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
