apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky.k8s.yaml
  - cert-manager.k8s.yaml
  - cilium.k8s.yaml
  - external-services.k8s.yaml
  - headscale.k8s.yaml
  - ingress.k8s.yaml
  - kube-system.k8s.yaml
  - mailserver.k8s.yaml
  - metallb.k8s.yaml
  - speedtest.k8s.yaml
  - unifi-controller.k8s.yaml
