apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rabbitmq/cluster-operator/config/installation?ref=v2.19.0
  - ./messaging-topology-operator
namespace: rabbitmq-operator
images:
  - name: rabbitmqoperator/cluster-operator
    newTag: 2.19.1
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: namespace-transformer
      namespace: rabbitmq-operator
    setRoleBindingSubjects: allServiceAccounts
