# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: messaging-topology-operator
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/rabbitmq/messaging-topology-operator.git
  sparseCheckout:
    - config
  ref:
    tag: v1.18.3
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: messaging-topology-operator-upstream
  namespace: flux-system
spec:
  interval: 10m
  path: ./config/installation/cert-manager
  targetNamespace: rabbitmq-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: messaging-topology-operator
  patches:
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: rabbitmq-system
    - patch: |
        - op: replace
          path: /subjects/0/namespace
          value: rabbitmq-operator
      target:
        kind: "(RoleBinding|ClusterRoleBinding)"
