apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rabbitmq/messaging-topology-operator/config/installation/cert-manager?ref=v1.18.3
images:
  - name: rabbitmqoperator/messaging-topology-operator
    newTag: 1.18.3
patches:
  - path: ./delete-ns-patch.yaml
