apiVersion: crossplane.emnt.dev/v1alpha1
kind: BackupBucket
metadata:
  name: backup-buckets
  namespace: mealie
spec: {}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: local-backup-s3
  namespace: mealie
spec:
  retentionPolicy: "30d"
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  configuration:
    destinationPath: s3://mealie/
    endpointURL: https://backup-s3.${CLUSTER_DOMAIN}
    wal:
      compression: gzip
    s3Credentials:
      accessKeyId:
        name: local-backup-s3-key
        key: access_key
      secretAccessKey:
        name: local-backup-s3-key
        key: secret_key
