# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: argo-events
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/argoproj/argo-events.git
  sparseCheckout:
    - manifests
  ref:
    tag: v1.9.10
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-events-upstream
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/cluster-install
  targetNamespace: argo-events
  prune: true
  sourceRef:
    kind: GitRepository
    name: argo-events
