# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/apps/development/argo-workflows
  dependsOn:
    - name: democratic-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: emnt-ops
