apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: headplane-cookie-secret
  namespace: headscale
spec:
  length: 32
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headplane-cookie-secret
  namespace: headscale
spec:
  refreshInterval: "30m0s"
  target:
    name: headplane-cookie-secret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: headplane-cookie-secret
