apiVersion: v1
kind: Secret
metadata:
    name: headscale
    namespace: headscale
stringData:
    oidc_client_id: ENC[AES256_GCM,data:Cd/GW/6SW22kUM1ek80SjxJg7S2yRZA5tdynwhmgAqDdGOP3pWW8Nw==,iv:GDviSFKZYiK+sc/oH+RYqkSZL+IrUGRsOpxdKEauwAk=,tag:rOwWj06DC/4jFfmE2+vYuQ==,type:str]
    oidc_secret_key: ENC[AES256_GCM,data:unJUa9vAHWB8hmjGbRz5hY5oO6HnHdnK9vY46+eIF8TiwHkYIXsEoObM4kdVhwvwMc06Oyz4WHeegASfFvfhW425wpm3IH7zFsA3IJIh7IAalvCLMHU2Pn+CAMKC55OyfyuyB+h4MBG5NguNLFmcPfG9nwgmSnNw8seEJKiVAJg=,iv:uylUV8y91lVjpED7hheJXA3oKdOs51K/4O8zvlSed8w=,tag:AkiedpluMHaVnO6n0z+awA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dEx3cmFXU3EzWDZTMUJ2
            cWpkcldLOWg1OVNmdDBKOTVtSVBUMzhDTnlrCjBqbU94bjhuZEFtMUpxd2FUaG1s
            QVBlQnZIS0VLVUtZWXdFYkdlQ3gxSFUKLS0tIGxwOE5lVkhKTnpHZS9NM3o5dXZM
            cmRVV3NpWC9TTS9RMTZzNU51Wi9vN2cKzqFSntQ0ut7fKos+CHywTE9/A/OBqj3N
            istV8UwSDuOSR4bYIv42ABYXS2baMUTEPYEo5jY1fNtqyj7Oe5oDzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T06:48:14Z"
    mac: ENC[AES256_GCM,data:BDM3C+FoVRn89kt8q+U7UbpwA7skiyO6cz6rjGt3Bi0VL6RfJakKhtBggtwO3h7BmH0ouBgU9mQj5f65VLQEIRLfu0RGtfmxF04XHEvSJOqodt1EhTS7ChOR/hZnzuuFZgUDn+m1tGTOURy6yHzWhDje0h1CNiTfcQ564dUqJtM=,iv:FYE5lxbIdPFLxHy06f/PEYpb7kJXFbTcKZ9Hcnx4AIE=,tag:hPg+ys3Jm8vBZaTD1SHrgg==,type:str]
    pgp:
        - created_at: "2026-02-22T06:48:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//V0n2ZAW4fRZiSP5OCC5CSAk/+IHlwenOXUe5dcJVUilH
            xhhv+xTIczClwnn46IzTG320vCTtLBuXNfRGrVwEd7r+TIaEcuSmCHWWPSGPE9It
            slg66c01iH1m4Y6OMZDcUtSbPYKdduM+2nGqxtVXyjoi9furqzOn6+ErGb/PGLEA
            TiUY8sN/3GWmR1+Xx0Jt1+AqYpP1Jgl3/BOhrXuSfxkf25+KPAn5kdwto71BODX1
            zZWeRjQqvV4GmvsUUUc4ci3xpRebWf2ctTDnX5jC1p3GlR0kmpKan/jF3h6vxYKY
            7wHI/Q3tvWtOAKTHKBME8Hh/Sx289yo9TSSjOh6+fGgKVKBHLG0dv+32lfEf/0B4
            VKREUkMtD8gSRx/gxd4xn9rwdPaypK/Vubv5cnGHSSb2/0Sn6lvyDZRE9ppLTCcv
            Ws80+UCE0mvvHrgBvGRMhA8wAfJEDqHKr3dgrq/C6QIl74lsRsQN+/RZnfVucO71
            DLzlzoVoCarqcBdrffl0/wwWQpMCx94J8GJCVZhkMkjB0MRgQyks5yq3B5P3fuK0
            HyizyK+mqnSGhYu77Xn5NjnpsEcP6q68AsvgVYiANfPzmJ0lUXpp+riXmrIgQYrI
            C840/43/Hpc3XaQybscYhdIazu2jNmHvzBe57koyox1wW+0eDJEDw/rpg6ZumAvS
            XgGjh47oB9pomMVpvfUOYS1kNfWiYlZOJ2Ka/hTIZsuSI81BGe7aKuKobfeo5PjQ
            04WIJ6KhODoIQNqqth7PeJYLlqXs/ZQYva/jpvtbMM2G+87JeuIPeBcq7N26IMU=
            =yE+J
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: headplane
    namespace: headscale
stringData:
    headscale_api_key: ENC[AES256_GCM,data:NoAjQCZhKaPBdE+DddDwFQGv12cQOuxTlFsL2nHxGELIavPVPkyOLBhZZhW2c5gSwN46z8EA5Ga+8jQkhOoCJP/YDObtFedMKF04nPjiOuNW9qshxYap,iv:shSr2VBUk55DQUFmIHo69L++fVGPK6hwgGfrAtNPI70=,tag:dhihTdCbNVSWBLQmtlxUCg==,type:str]
    headscale_preauth_key: ENC[AES256_GCM,data:gWxIrd1st6Wgxu0cHFT4+63NZSoKv3fQJ2qWWAmCt24teN253cAs+YQB1InX61aAZ9mz++aRYbJ1akGEJ+2qhPpJcVJz523kPZJV1APKqNfAepLZHxFhgQ==,iv:gfgeQyQn2nkrSgJ/wBLDFPP5gTHLURI1GI17G5TkaII=,tag:4dTIctTpFBQflpifdpFPhA==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dEx3cmFXU3EzWDZTMUJ2
            cWpkcldLOWg1OVNmdDBKOTVtSVBUMzhDTnlrCjBqbU94bjhuZEFtMUpxd2FUaG1s
            QVBlQnZIS0VLVUtZWXdFYkdlQ3gxSFUKLS0tIGxwOE5lVkhKTnpHZS9NM3o5dXZM
            cmRVV3NpWC9TTS9RMTZzNU51Wi9vN2cKzqFSntQ0ut7fKos+CHywTE9/A/OBqj3N
            istV8UwSDuOSR4bYIv42ABYXS2baMUTEPYEo5jY1fNtqyj7Oe5oDzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T06:48:14Z"
    mac: ENC[AES256_GCM,data:BDM3C+FoVRn89kt8q+U7UbpwA7skiyO6cz6rjGt3Bi0VL6RfJakKhtBggtwO3h7BmH0ouBgU9mQj5f65VLQEIRLfu0RGtfmxF04XHEvSJOqodt1EhTS7ChOR/hZnzuuFZgUDn+m1tGTOURy6yHzWhDje0h1CNiTfcQ564dUqJtM=,iv:FYE5lxbIdPFLxHy06f/PEYpb7kJXFbTcKZ9Hcnx4AIE=,tag:hPg+ys3Jm8vBZaTD1SHrgg==,type:str]
    pgp:
        - created_at: "2026-02-22T06:48:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//V0n2ZAW4fRZiSP5OCC5CSAk/+IHlwenOXUe5dcJVUilH
            xhhv+xTIczClwnn46IzTG320vCTtLBuXNfRGrVwEd7r+TIaEcuSmCHWWPSGPE9It
            slg66c01iH1m4Y6OMZDcUtSbPYKdduM+2nGqxtVXyjoi9furqzOn6+ErGb/PGLEA
            TiUY8sN/3GWmR1+Xx0Jt1+AqYpP1Jgl3/BOhrXuSfxkf25+KPAn5kdwto71BODX1
            zZWeRjQqvV4GmvsUUUc4ci3xpRebWf2ctTDnX5jC1p3GlR0kmpKan/jF3h6vxYKY
            7wHI/Q3tvWtOAKTHKBME8Hh/Sx289yo9TSSjOh6+fGgKVKBHLG0dv+32lfEf/0B4
            VKREUkMtD8gSRx/gxd4xn9rwdPaypK/Vubv5cnGHSSb2/0Sn6lvyDZRE9ppLTCcv
            Ws80+UCE0mvvHrgBvGRMhA8wAfJEDqHKr3dgrq/C6QIl74lsRsQN+/RZnfVucO71
            DLzlzoVoCarqcBdrffl0/wwWQpMCx94J8GJCVZhkMkjB0MRgQyks5yq3B5P3fuK0
            HyizyK+mqnSGhYu77Xn5NjnpsEcP6q68AsvgVYiANfPzmJ0lUXpp+riXmrIgQYrI
            C840/43/Hpc3XaQybscYhdIazu2jNmHvzBe57koyox1wW+0eDJEDw/rpg6ZumAvS
            XgGjh47oB9pomMVpvfUOYS1kNfWiYlZOJ2Ka/hTIZsuSI81BGe7aKuKobfeo5PjQ
            04WIJ6KhODoIQNqqth7PeJYLlqXs/ZQYva/jpvtbMM2G+87JeuIPeBcq7N26IMU=
            =yE+J
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
