apiVersion: v1
kind: Secret
metadata:
    name: headscale
    namespace: headscale
stringData:
    oidc_client_id: ENC[AES256_GCM,data:uTYakegHrxCrzIEb6VDcKZrZgh14P61pK6r9c2wX8gPTaUkOBk8J/A==,iv:j5ePfB7RTTcfLivhQsyT48xfWZa26++BWlJ9bK1fsTk=,tag:q5COsTVCF7ARwRIsel49xQ==,type:str]
    oidc_secret_key: ENC[AES256_GCM,data:/OU+Cf4exalwrHl61i51MnydD/hJA5c1/3x08uF6PvhU1MIq/DRrqyTKYJ8WT/MKcPgdg9DEN/bXcencLN7Y0e8vyww0cN9T7KcY0SjrAjF232Ts88T0XJDtyoS76YA/0Hs8JpTKb7Ut3+NTvKvcoevcdl+b5n9ZTPxe9hatWmQ=,iv:knZN4/p2BJPLakTOaTq1WkMqG7YYsr+L70k66mrpJbg=,tag:TWgSaNy0k8i5LVcjlB/N7A==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNFFOa1BkTklzMjlPN2hS
            Z3ZkRU12WGl6a3pzRnN4UHpGbjVqTnM1R0ZNCnR1RUVyNEVmOFVFcTh5bmVQRkQ5
            UU5zN2dzdENDOHQ2dFRYYy9NOTRUa1EKLS0tIFFZVVVmWGo0SDB6RTdRSkVkOUhF
            TVIyOUlUVWNuSmZhWFRqSHhIMXAzY1EKIu7nrDLkA/UF+QgQDIAV9ulPsZZODNZs
            KVOrkdCHtACTPYKKS11Lk9Rsn4nvHVGkMHJ1oSSobL6iVHdGlZZLog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T21:21:50Z"
    mac: ENC[AES256_GCM,data:dKH61BIwXGkSRDgW4KcSWg9CyMqeEsG2LER5qHOSFH4gs0lD6p5KvicEjFcdajBJfP3Gq3a16i99nyVEwgin69IXYVNqY5hSIsKYOpmV/oMy8ILKgx2CReq1Tt7kZe07n0+CL5DSgqobdB1o6B1Vq0dGfYJd/vxh5130tv5iPv4=,iv:rr0ptiCBzRehEoTePL5c1V/W3cgWymKYpXj6QmUHJHk=,tag:Zvw0eLslCh6klNoHvG11Nw==,type:str]
    pgp:
        - created_at: "2026-02-22T21:21:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//ep0dBKiNiV+EyKKg0/IOE3N1Rpj1ApUHCahsB2/29mDl
            frMqUGgOQqboWJ1SAzIS/uSPRbiGgAq2tsb2g63goWo2+LRzpzMLPWUK3BlPw9TT
            s+Ur2sP7JaVUgr0A03zK4NO11poUXkGBwnImnJD94Wwivx6I0rDJbY78j4K6WRa/
            HDHrWJ6mybWojU+mI9/X47LXYLBEivmE+Dhlb73gLtfYnkqK8aljehl5/DggeArF
            R2zQpXqc+OKuWKj2Z9LuQEDZRx+4BJFLETZW1g+f1rTEsweo3Ip/jZBw2DC+wPZ/
            dp6+PHmhuPUZiM6au41jHz/tKzjXZ+mO9JB8vLnLyzu3OFOtbmQk4PXOtXSLm1iH
            CuI/XFfC3psEjHKXZ0XkOznqTsjMstWciZNe4f0UktxlSNhO3cCIwnr9stJnhqS2
            WxHJvz+KHkBQZNoyRpvlE1BQeON0O6kSDlX047nMYgjTvlbsxPpkN/+45WrTH4vF
            lLkeIbsUHkFSqMVkpLf/ZSSJFlY62NPPoJHsX/ucBc4JeP6WIyS2yUuGPBO5Xtro
            XcXV1mTOqrY14U3yEGdM66crWfbhqCqmAHe9AMf7OyRV0CUwt/ZPVXZ/of5TnSGo
            xvVpBD9WWDXQWtQNp0I8c7Zuv9kP6a/zoGnaScKYZx8aNWqvldVRQIEbMNIaw6HS
            XgHi2kIJhLYjEJFU/6ariqlJ5ivk6Q+R5dTDpsIwey6RGnRKWBxFASNg2jxP7jy1
            dDwOkcbmJL+wduFi3sccxNiDfUM0kuXh9wfLvle1y0ygWOJ9zpzpvATprxEGSec=
            =mkty
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: headplane
    namespace: headscale
stringData:
    headscale_api_key: ENC[AES256_GCM,data:t3z/mVFO8meAnFFVfCjnG3hvm1wbtGxzA6VtbkiAqcWf1AmVw8fEj/YkdT/7xTP9IyFwMTfvdMx+LentPSwMvOBCLVCxc57MNs3QkHRiszWOTvGvz0Se,iv:mmaFcfn7TupoCpmN3CiVGlBhWAEjRtpQtC5/LDTdUus=,tag:tRIPBZo8B8M3coupTa2N/Q==,type:str]
    headscale_preauth_key: ENC[AES256_GCM,data:qOHiVbKZUH+h6zwkug4x9M8y6ci5Y6E2tgg9X7B1bGRYL6HQUOiCAu32imFUd9r2eQRwGqy/+o5ddY/Yd1qRfqfk+qX9mGGmBy1hsTTKV6JrS1fsl7F+Mg==,iv:HKivaQPCqQK3oeUm/mnbeNHYEUAoVfos2NIx4Br84Hc=,tag:dNiHlF4mNlVHon/2qPNmqw==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNFFOa1BkTklzMjlPN2hS
            Z3ZkRU12WGl6a3pzRnN4UHpGbjVqTnM1R0ZNCnR1RUVyNEVmOFVFcTh5bmVQRkQ5
            UU5zN2dzdENDOHQ2dFRYYy9NOTRUa1EKLS0tIFFZVVVmWGo0SDB6RTdRSkVkOUhF
            TVIyOUlUVWNuSmZhWFRqSHhIMXAzY1EKIu7nrDLkA/UF+QgQDIAV9ulPsZZODNZs
            KVOrkdCHtACTPYKKS11Lk9Rsn4nvHVGkMHJ1oSSobL6iVHdGlZZLog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T21:21:50Z"
    mac: ENC[AES256_GCM,data:dKH61BIwXGkSRDgW4KcSWg9CyMqeEsG2LER5qHOSFH4gs0lD6p5KvicEjFcdajBJfP3Gq3a16i99nyVEwgin69IXYVNqY5hSIsKYOpmV/oMy8ILKgx2CReq1Tt7kZe07n0+CL5DSgqobdB1o6B1Vq0dGfYJd/vxh5130tv5iPv4=,iv:rr0ptiCBzRehEoTePL5c1V/W3cgWymKYpXj6QmUHJHk=,tag:Zvw0eLslCh6klNoHvG11Nw==,type:str]
    pgp:
        - created_at: "2026-02-22T21:21:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//ep0dBKiNiV+EyKKg0/IOE3N1Rpj1ApUHCahsB2/29mDl
            frMqUGgOQqboWJ1SAzIS/uSPRbiGgAq2tsb2g63goWo2+LRzpzMLPWUK3BlPw9TT
            s+Ur2sP7JaVUgr0A03zK4NO11poUXkGBwnImnJD94Wwivx6I0rDJbY78j4K6WRa/
            HDHrWJ6mybWojU+mI9/X47LXYLBEivmE+Dhlb73gLtfYnkqK8aljehl5/DggeArF
            R2zQpXqc+OKuWKj2Z9LuQEDZRx+4BJFLETZW1g+f1rTEsweo3Ip/jZBw2DC+wPZ/
            dp6+PHmhuPUZiM6au41jHz/tKzjXZ+mO9JB8vLnLyzu3OFOtbmQk4PXOtXSLm1iH
            CuI/XFfC3psEjHKXZ0XkOznqTsjMstWciZNe4f0UktxlSNhO3cCIwnr9stJnhqS2
            WxHJvz+KHkBQZNoyRpvlE1BQeON0O6kSDlX047nMYgjTvlbsxPpkN/+45WrTH4vF
            lLkeIbsUHkFSqMVkpLf/ZSSJFlY62NPPoJHsX/ucBc4JeP6WIyS2yUuGPBO5Xtro
            XcXV1mTOqrY14U3yEGdM66crWfbhqCqmAHe9AMf7OyRV0CUwt/ZPVXZ/of5TnSGo
            xvVpBD9WWDXQWtQNp0I8c7Zuv9kP6a/zoGnaScKYZx8aNWqvldVRQIEbMNIaw6HS
            XgHi2kIJhLYjEJFU/6ariqlJ5ivk6Q+R5dTDpsIwey6RGnRKWBxFASNg2jxP7jy1
            dDwOkcbmJL+wduFi3sccxNiDfUM0kuXh9wfLvle1y0ygWOJ9zpzpvATprxEGSec=
            =mkty
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
