apiVersion: v1
kind: Secret
metadata:
    name: headscale
    namespace: headscale
stringData:
    oidc_secret_key: ENC[AES256_GCM,data:NAUzYjuxT2tXXlcz/QQNqwDGkjMLONV0GUnC8N5vdkuwAwSB44WpXQwrCYcY7jFWeO6N9bEaVIIYvZ4i4DeG8jeRLzG1RIi3kF7X91MtW6BTZZSrHpr41ZE6VXwkggO2brigZapgzKMDSVNqZTGR0x7KzmnIUaDpem5ZTL+5K9E=,iv:O6/ecOuKeiAtkEk7xZEHKpCzGcfanq3h9ukqJ/3B9Jc=,tag:NZuvGePEZSs7MroyZTSdDg==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WnRGMGlvWE5xL0tYYXMv
            OHp6TXF2SjQ3U1Y3bXNCajg1NUV3UnI2QWxNCmZFT1JZR1g4ZS9qdXJ5NXVRRnQv
            bHJ6R2hTOGtjREQrMmtMelozb3hyM00KLS0tIG8wdDQraXJzQ2FudTEzd2dxM0hN
            bUhWK2xRM25OZWplTTVGbEYrcTNKWk0KhtaRTC3nfrGBTuGajEFCVesYaTFXlCfc
            GwajQ9DX6xsWOmqFuAL+ukJqnelzGDQWwbi9WnSCS6/Np5fu99JG5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T02:21:17Z"
    mac: ENC[AES256_GCM,data:eCpuqQWaEL5IW/VaSPT5gfdDyi7Yl7RW/hgfHm3Tkxt9U/eBnTvixeFc0hRfnxn/uesmRU/FL8hRGt+orD7aqNaUwPltISurXFC33yv/S0QE8LOLIT19VmgM8dnJjmIoKd7M55Rg/R+GmbasX9AFrPFB8IK5vIKX5g/vKG/LbHQ=,iv:XGtjz0wNg57XKQViIpRYVzVjV/cwK5IGKe+1jmwkNec=,tag:DbqImEzwSSBs8mcYL1I4gQ==,type:str]
    pgp:
        - created_at: "2025-11-15T02:21:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOARAAhOOdkR0SZ/mRunrsVqlnfuq5Wk/1iG+iDCd2Wf9Ygt5+
            s0SdezLexKB5M1834eiHron6oNbqJOmhbnnTYRU8mgSygJgKC6wFrLdRibGxJCzg
            MHW1ah+uuMjUY5J4XfTdYrqLC6kIYbNon6TPqg8qLI1dAWjSgocM+g0i3XrXXktL
            U+r37hGNbxtV4bFF42t7LqO002Vk8g7OO6TastmY7D0jfIL+UhN5ayqS2eRo0pgW
            TWNke/N9sz2P7PJeSx7pyi+2YshCYLZFfmnIZJMZoOxSJyGLDmz6LTerC7yrYLjR
            KONMGo5T1ncQAtOPaF8RWozXSjHpwwX/ksQHzbywKnp/X7SHxe3wu4IxVbwD9PqI
            +YP4Ej7TCLpw2O44I3rvl4l5sia3lMIAyIqczvDxkFtEkCfVO2TEdNrNCnHLlXY6
            vyoS/n8XBLfEaVfyhk/hKFiH88be4ZH1j860hNkgd88+BxM9HC/om1thbLm2FatB
            YZ6/PS+2VAxsKvz6ILO1ly3+lUk0aQd+PsOPAktAwI6bQvci4cs7JxMHwCl6XPh0
            QBz56+eFFGUnqUFXmAPSn760PKCihhhtdLJpRgZs/IIEbzVnk4s7YrSvy79JAKFm
            cimXFzxE73jGlFabcTiWd5lzy8VGKPcq29U3MnEAQBOzlCF7cWHu1wEkzmUgk77S
            XgGbKwVT+MWdpTwVnzfEXqMJUGgS7B1VKe1A6mFy1PWf8fZsQCstYjjmbqq0lnuT
            3DkYaEVRn6PFeWuQSNYX/shTW/DLnM0Q+YduJDnxjODXezKjq6BFDfzOUkJA/JU=
            =R1O0
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
