apiVersion: v1
kind: Secret
metadata:
    name: headscale
    namespace: headscale
stringData:
    oidc_client_id: ENC[AES256_GCM,data:/U+2nO/BBt26bfi7QC0eDKHzKyQoSqLVYnYvrLQaO0grZwJ3GAdY7Q==,iv:lGYKe3oBYPahup6gS28uRQ3I4eZhy8kYnQySYt6Qc7M=,tag:bYuFUerkyP6NaVIMvGiTAA==,type:str]
    oidc_secret_key: ENC[AES256_GCM,data:M67ofHY551oLAkGrWI6by/YNjZwHb1XGS9rs7q14TE99ybbYESYLx03j+vggzNaeOPNX4CvLU28DZkokpGDDz3zXKpfbvG8bGl7fhI3YbeSp7hnTrdUxDLcCfuu/Pky65opkSq1k1fTLbrBh0iq86Ja3hNsmUZyb1JifoFFRizc=,iv:9fNpKrXX90Ohn4SFcbxwUH7uMqu5diuxvJb3toxvlm0=,tag:paFD30ARLFMY9kaHpGGp5w==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL1dQN0JKZU9oWEMvdEFF
            WWRsTUdkN3NiUG5UT1lobXFuMG9MUWtmZzNjCnlRTFRaOFR5Wko2akVRR3VIYnJv
            OVErSUhlSWd5UkpJOG1hc2NZOS8wQkEKLS0tIGYvQ0FSd1pqcUwzbVlYaEpkbzV0
            R1diOG9JUFh3NkhOU2o0VkZUZlhwN1EKfzHaVHHgWIgfB8i2iDduEeln7iw1Trqy
            /QV0nJ8seP8R/ntHziGdkeW/fc+hg0oLdw2zaALrYYvLdSyyBI4DHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T08:57:07Z"
    mac: ENC[AES256_GCM,data:J2SZvtWTmUktP6pnKLpQuwONLtq6J2rYS9tfBygegyzx1KsqtmNEhxqvt72kmQTkZaQAeBMfv4Jhlu06XSaJE8e63XF2P6CYM6eJGkv/SfpRh1wrFcGbqF75K713Gd5Zm2WjhiRG4V/hmfKnlD+kWEBytQGTibWZESkw+88wt0c=,iv:K74jTdqvpO2mn5utsNlCygw4q1LZ4zppiurXgnKf+MY=,tag:bPwX1/V3aNT185lWkBWm3A==,type:str]
    pgp:
        - created_at: "2026-02-22T08:57:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//dR4VXiPsEXt+X2+nQvn0OMz7AdRMcJosddY9wTFXyAx2
            4Lem+iuz8JgdXeyErG+WSfChYkYiVHKTGOeuIhMSkvMaZgpWlBBcFT4XsBssIbwm
            NJuUmtJ8h3MkBZRkMZNOXWuf/rZQih7rSHs6Laxs+b1uO8McOcBluaGBjvE8h1jk
            Teomy8DqP6S8AU0Jx6Istw4AbYqzmgY+zGI9vCp4/cAiHAiYz4IxcbV4HOCptyr3
            kE9dsme6cbsQxKktmwDvMuzpYdeA/pME4HZ3it6umwCjFoDTUFf3kWB8gTkhGOOR
            +ssbdu52T+9SuCgZzYJLsEWF/b/SwuBaSqd1Uzb3bYvYNR3qQ8U+CnvNkK69oH2p
            OHGXQ1v2eyCnVC6uFKB61mUJYWgHpQkEhDtdy6P7sjDnVfkIE9/ChKNU3QW91fAg
            Wo8Miv/2x9siOTG0ne+PEUyeDkhkN9q1ZSLj82wGH9il2hIwEkiofCiYG3Nyn0YC
            +uu261iMA3NV6vdNPhx9pl4XLkHqqDtwFcswhocXAMST/fs/YYIpVq9qQlh3htv3
            BEDaYKCJk6iU8zSQtfqfmROmxjVqWGeoW+W1SIVdI7sTokj4S0THFWWiEt64cZKK
            4yLkhZJT6d44+V+L/myBwwf4sywnjQd0d7db4xlClCljET3TzKZafBl6JfZQvg/S
            XgGFUQz9eFMkytKHfO81C4HT8wsVZm3Zgh7HzolNps76Jq6UXEzv2zzJ/my0BgeB
            8lpWawskxK60HVI/NFDPb7TxfKuedFPzusX1ZSlfmYkX8zlfEuCfmvBwBphD3Fo=
            =YEty
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: headplane
    namespace: headscale
stringData:
    headscale_api_key: ENC[AES256_GCM,data:7iJBD7xEJJBbCvpU+coFdUw6Wwew64K2dx+40QbD9XDdhwrmol/mEB8XthLVNFgOjHSG/0MrLaFIJ7DtInA6XWq+1NwbyAAgToh9pBHwn387HgNfYtF+,iv:zHFPDX2DtxlOqmAgYkzep29D9W6IdoeaqoEiaQarvEs=,tag:shEkrCsx2Bnf8fQ3KIv0AQ==,type:str]
    headscale_preauth_key: ENC[AES256_GCM,data:meGFZVBwu6gpqVfV7z2mYSylI4m4MbNrg0Uh7OXOfFZAvUU/P5EScHcB6fW3ZXYKmOAGE133FnJAd9aZjRlniJQxb3+m9nZ6TMpUd2crTK8dd2leFzP6bA==,iv:ShaPhjAr8xy1JYFTOUZehUXU1G4y2a+NZwzbRtHIVcs=,tag:22nUhA3O45GoRo01QT4CnQ==,type:str]
sops:
    age:
        - recipient: age1exncnhces66v0uc67xm009v2d2237hgdxtaa8tdy0hvusexjry0qye4ad2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL1dQN0JKZU9oWEMvdEFF
            WWRsTUdkN3NiUG5UT1lobXFuMG9MUWtmZzNjCnlRTFRaOFR5Wko2akVRR3VIYnJv
            OVErSUhlSWd5UkpJOG1hc2NZOS8wQkEKLS0tIGYvQ0FSd1pqcUwzbVlYaEpkbzV0
            R1diOG9JUFh3NkhOU2o0VkZUZlhwN1EKfzHaVHHgWIgfB8i2iDduEeln7iw1Trqy
            /QV0nJ8seP8R/ntHziGdkeW/fc+hg0oLdw2zaALrYYvLdSyyBI4DHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T08:57:07Z"
    mac: ENC[AES256_GCM,data:J2SZvtWTmUktP6pnKLpQuwONLtq6J2rYS9tfBygegyzx1KsqtmNEhxqvt72kmQTkZaQAeBMfv4Jhlu06XSaJE8e63XF2P6CYM6eJGkv/SfpRh1wrFcGbqF75K713Gd5Zm2WjhiRG4V/hmfKnlD+kWEBytQGTibWZESkw+88wt0c=,iv:K74jTdqvpO2mn5utsNlCygw4q1LZ4zppiurXgnKf+MY=,tag:bPwX1/V3aNT185lWkBWm3A==,type:str]
    pgp:
        - created_at: "2026-02-22T08:57:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwVH6sRf6ijOAQ//dR4VXiPsEXt+X2+nQvn0OMz7AdRMcJosddY9wTFXyAx2
            4Lem+iuz8JgdXeyErG+WSfChYkYiVHKTGOeuIhMSkvMaZgpWlBBcFT4XsBssIbwm
            NJuUmtJ8h3MkBZRkMZNOXWuf/rZQih7rSHs6Laxs+b1uO8McOcBluaGBjvE8h1jk
            Teomy8DqP6S8AU0Jx6Istw4AbYqzmgY+zGI9vCp4/cAiHAiYz4IxcbV4HOCptyr3
            kE9dsme6cbsQxKktmwDvMuzpYdeA/pME4HZ3it6umwCjFoDTUFf3kWB8gTkhGOOR
            +ssbdu52T+9SuCgZzYJLsEWF/b/SwuBaSqd1Uzb3bYvYNR3qQ8U+CnvNkK69oH2p
            OHGXQ1v2eyCnVC6uFKB61mUJYWgHpQkEhDtdy6P7sjDnVfkIE9/ChKNU3QW91fAg
            Wo8Miv/2x9siOTG0ne+PEUyeDkhkN9q1ZSLj82wGH9il2hIwEkiofCiYG3Nyn0YC
            +uu261iMA3NV6vdNPhx9pl4XLkHqqDtwFcswhocXAMST/fs/YYIpVq9qQlh3htv3
            BEDaYKCJk6iU8zSQtfqfmROmxjVqWGeoW+W1SIVdI7sTokj4S0THFWWiEt64cZKK
            4yLkhZJT6d44+V+L/myBwwf4sywnjQd0d7db4xlClCljET3TzKZafBl6JfZQvg/S
            XgGFUQz9eFMkytKHfO81C4HT8wsVZm3Zgh7HzolNps76Jq6UXEzv2zzJ/my0BgeB
            8lpWawskxK60HVI/NFDPb7TxfKuedFPzusX1ZSlfmYkX8zlfEuCfmvBwBphD3Fo=
            =YEty
            -----END PGP MESSAGE-----
          fp: C5B9ADB07DBE5A2E
    encrypted_regex: ^(data|stringData|crowdsecLapiKey)$
    version: 3.11.0
