# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/argoproj/argo-workflows.git
  sparseCheckout:
    - manifests
  ref:
    tag: v4.0.1
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows-upstream
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/cluster-install
  targetNamespace: argo-workflows
  dependsOn:
    - name: democratic-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: argo-workflows
