apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hardware
  - monitoring
  - multimedia
  - network
  - operators
  - security
  - smart-home
  - storage
  - development
  - communications
  - accounting
